### ISSUE TITLE
Shortcuts not working properly in Tabs after changing sth in grid view + [Tab]

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend-legacy#1949]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When you have changed sth in a tab, in grid view, shortcuts like e.g. `alt`+e or `alt`+y don't work anymore.
#### Which are the steps to reproduce?
1. Open bpartner window/123,for e.g. Test Kunde, select location tab
2. try `alt`+e: advanced edit opens: OK
3. try `alt`+y: modal opens if you want to delete data: OK
4. change sth in the grid view, e.g. name of the location, use `Tab`
5. try the shortcuts again:
* [alt]+y: console: bundle-68a8b26b41afac1887dc-git-88660db.js:77 Handler defined for key sequence "ALT+Y" is not a function.: NOK
* `alt`+e: advanced edit for the header opens: NOK

http://recordit.co/2Fmf9l1aCq

=> works fine when you change sth in advanced edit
=> when you use `Enter` after the change you made, `alt`+y works fine, but `alt`+e also opens the advanced edit for the header

=> also happened in sales order, when i changed sth in orderline

**Comment by siemiatj** [comment]
imho we almost have no bugs here. Simply Table shortcuts work only when something is selected, and window shortcuts when something isn't. One bug I've found is when opening window, going to locations (or other tab with results) and clicking `[alt]+y`. This triggers a delete without anything to delete. Other than that : 
- to get the `[alt]+e` working just deselect rows (by changing tabs for example),
- to get the `[alt]+y` working, select a row

**Comment by metas-dh** [comment]
checked with metas-mk:
=> In my case, it's confusing when after e.g. changing the name of a location, in baprtner window, the row in location tab is still selected (or at least looks like it is), but the `[alt]+e` does not open advanced edit for this line. Of course the user could deselect rows / change tabs and then select and use `[alt]+e` once more for the row where they made changes, but it's not very intuitive / not very nice. 
However, this is not high prio at all, so pls leave it for when there are no more urgent tasks, and pls do an estimation before getting back to this task so we can decide if it's worth the effort.

**Comment by metas-dh** [comment]
this is working correctly since the big refactoring.
