### ISSUE TITLE
Sales order button multiplied in invoice candidates

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend-legacy#2305]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When you open invoice candidates from sales order, there is a button showing this order in the window, and the ICs are filtered for this order, OK. If you add further filters, that button is multiplied: in my case, i also filtered for date and currency:

![2019-06-24 17_31_37-NotificationsForm](https://user-images.githubusercontent.com/18696715/60032087-27eb9980-96a6-11e9-82d9-172d851384e3.png)

**Update:**
happens also in purchase window, e.g. opening the PO from refrences in material receipt, adding filters for date & reference: 

![2019-09-04 10_47_47-NotificationsForm](https://user-images.githubusercontent.com/18696715/64240109-ab750280-cf01-11e9-8103-46b3dd3419cb.png)

#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
Show the sales order button only once.

**Note:** not sure this happens with other windows too.

**Comment by TheBestPessimist** [comment]
Will be fixed in: https://github.com/metasfresh/metasfresh/issues/10030
